---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: environment-automation
- name: terraform-state

outputs:
- name: create-infrastructure-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_DNS_ZONE_NAME:
  GCP_DNS_ZONE_DNS_NAME:
  PKS_CLUSTER_NAME:
  CREDHUB_SERVER:
  CREDHUB_CA_CERT:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  PREFIX:

run:
  path: environment-automation/tasks/create-infrastructure/task.sh
