groups:
- name: full-pcf
  jobs:
  - fetch-platform-automation
  - bootstrap-terraform-state
  - create-infrastructure
  - wipe-env
  - deploy-opsman
  - configure-director
  - apply-changes-director
  - export-installation
  - upload-and-stage-pas
  - upload-stemcell-pas
  - generate-product-config-pas
  - configure-product-pas
  - disable-errands-pas
  - apply-product-changes-pas
  - export-installation-pas
- name: infrastructure
  jobs:
  - bootstrap-terraform-state
  - create-infrastructure
  - wipe-env
  - deploy-opsman
  - configure-director
  - apply-changes-director
  - export-installation
- name: pks
  jobs:
- name: pas
  jobs:
  - upload-and-stage-pas
  - upload-stemcell-pas
  - generate-product-config-pas
  - configure-product-pas
  - disable-errands-pas
  - apply-product-changes-pas
  - export-installation-pas
- name: manage-env
  jobs:
- name: bootstrap-demos
  jobs:

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: daily
  type: time
  source:
    interval: 24h
- name: terraform-state
  type: gcs-resource
  source:
    bucket: ((gcp.bucket))
    json_key: ((gcp.json_key))
    versioned_file: terraform.tfstate
- name: environment-automation
  type: git
  source:
    uri: ((github.configuration_uri))
    branch: master
    private_key: ((github.key))
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 2\.(.*)
    sort_by: semver
- name: platform-automation-tasks
  type: gcs-resource
  source:
    bucket: ((gcp.bucket))
    json_key: ((gcp.json_key))
    regexp: platform-automation-tasks-(.*).zip
- name: platform-automation-image
  type: gcs-resource
  source:
    bucket: ((gcp.bucket))
    json_key: ((gcp.json_key))
    regexp: platform-automation-image-(.*).tgz
- name: installation
  type: gcs-resource
  source:
    bucket: ((gcp.bucket))
    json_key: ((gcp.json_key))
    regexp: installation-after-(.*).zip
- name: om-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((products.opsman.product_slug))
    product_version: ((products.opsman.product_version))
    sort_by: semver
- name: pas-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((products.pas.product_slug))
    product_version: ((products.pas.product_version))
    sort_by: semver
- name: pas-stemcell
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((products.pas.stemcell.product_slug))
    product_version: ((products.pas.stemcell.product_version))
    sort_by: semver

# reusable stuff
credhub-interpolate: &credhub-interpolate
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: environment-automation
  params:
    CREDHUB_SERVER: ((credhub.server))
    CREDHUB_CA_CERT: ((credhub.ca_cert))
    CREDHUB_CLIENT: ((credhub.client))
    CREDHUB_SECRET: ((credhub.secret))
    PREFIX: /concourse/((foundation))
    INTERPOLATION_PATH: ((credhub.interpolate_folders))

jobs:
- name: bootstrap-terraform-state
  serial: true
  ensure:
    put: terraform-state
    params:
      file: bootstrap-output/*.tfstate
  plan:
  - get: environment-automation
  - task: create-terraform-state
    params:
      TERRAFORM_STATEFILE_BUCKET: ((gcp.bucket))
      GCP_SERVICE_ACCOUNT_KEY: ((gcp.json_key))
    file: environment-automation/tasks/create-initial-terraform-state/task.yml

- name: wipe-env
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: wipe-output/*.tfstate
  plan:
  - aggregate:
    - get: environment-automation
    - get: terraform-state
  - task: wipe
    file: environment-automation/tasks/wipe-env/task.yml
    params:
      GCP_PROJECT_ID: ((gcp.project))
      GCP_REGION: ((gcp.region))
      GCP_SERVICE_ACCOUNT_KEY: ((gcp.json_key))

- name: create-infrastructure
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: create-infrastructure-output/*.tfstate
  plan:
  - aggregate:
    - get: terraform-state
    - get: environment-automation
  - task: create-infrastructure
    file: environment-automation/tasks/create-infrastructure/task.yml
    params:
      GCP_PROJECT_ID: ((gcp.project))
      GCP_REGION: ((gcp.region))
      GCP_SERVICE_ACCOUNT_KEY: ((gcp.json_key))
      GCP_DNS_ZONE_NAME: ((gcp.dns_zone_name))
      GCP_DNS_ZONE_DNS_NAME: ((gcp.dns_zone_dns_name))
      PKS_CLUSTER_NAME: ((pks.cluster_name))
      CREDHUB_SERVER: ((credhub.server))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.secret))
      PREFIX: "/concourse/((foundation))"
      SSL_CERT: ((pas.ssl.cert))
      SSL_PRIVATE_KEY: ((pas.ssl.private_key))
      AZ_LIST: ((gcp.az_list))
      CREATE_GCS_BUCKETS: ((gcp.create_buckets))

- name: deploy-opsman
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: om-product
      params:
        globs:
        - "((products.opsman.product_globs))"
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: create-vm
    image: platform-automation-image
    file: platform-automation-tasks/tasks/create-vm.yml
    input_mapping:
      image: om-product
      state: environment-automation
      config: environment-automation
      vars: interpolated-files
    params:
      OPSMAN_CONFIG_FILE: ((foundation))/products/((products.opsman.product_slug))
      VARS_FILES: vars/((foundation))/vars/((products.opsman.product_slug)).yml
      STATE_FILE: ((foundation))/state/state.yml
    on_success:
      do:
        - task: make-commit
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: environment-automation
            file-source: generated-state
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: state.yml
            FILE_DESTINATION_PATH: ((foundation))/state/state.yml
            GIT_AUTHOR_EMAIL: ((github.user.email))
            GIT_AUTHOR_NAME: ((github.user.username))
            COMMIT_MESSAGE: "Add or update state file: state.yml"
        - put: environment-automation
          params:
            repository: configuration-commit
            merge: true
  - task: configure-authentication
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-authentication.yml
    attempts: 10
    input_mapping:
      env: interpolated-files
      config: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/((products.opsman.product_slug)).yml
      AUTH_CONFIG_FILE: ((foundation))/config/auth.yml
    on_success: &make-config-commit
      do:
        - task: staged-director-config
          image: platform-automation-image
          file: platform-automation-tasks/tasks/staged-director-config.yml
          input_mapping:
            env: interpolated-files
          params:
            ENV_FILE: ((foundation))/env/((products.opsman.product_slug)).yml
        - task: make-commit
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: environment-automation
            file-source: generated-config
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: director.yml
            FILE_DESTINATION_PATH: ((foundation))/generated-config/director-((products.opsman.product_version))
            GIT_AUTHOR_EMAIL: ((github.user.email))
            GIT_AUTHOR_NAME: ((github.user.username))
            COMMIT_MESSAGE: "Add or update product config: director-((products.opsman.product_version))"
        - put: environment-automation
          params:
            repository: configuration-commit
            merge: true

- name: configure-director
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      passed: [deploy-opsman]
      params: {unpack: true}
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: configure-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-director.yml
    input_mapping:
      config: environment-automation
      env: interpolated-files
      vars: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/((products.opsman.product_slug)).yml
      DIRECTOR_CONFIG_FILE: ((foundation))/products/director
      VARS_FILES: vars/((foundation))/vars/director.yml

- name: apply-changes-director
  serial: true
  serial_groups: [install-om]
  plan:
  - aggregate:
    - get: platform-automation-image
      passed: [configure-director]
      params: {unpack: true}
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/ops-manager.yml

# 4 export-installation
- name: export-installation
  serial: true
  serial_groups: [install-om]
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [apply-changes-director]
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: export-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/ops-manager.yml
      INSTALLATION_FILE: installation-after-((products.opsman.product_slug))-((products.opsman.product_version)).zip
  - put: installation
    params:
      file: installation/installation-after-((products.opsman.product_slug))-((products.opsman.product_version)).zip

- name: fetch-platform-automation
  # We use the pivnet resource to bootstrap the pipeline,
  # and because this product is part of the pipeline, not the foundation
  plan:
  - get: daily
    trigger: true
  - get: platform-automation-pivnet
  - aggregate:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz

- name: upload-and-stage-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: pas-product
      params:
        globs:
        - "((products.pas.product_globs))"
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: upload-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: pas-product
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
  - task: stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: pas-product
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
  - task: staged-config
    image: platform-automation-image
    file: platform-automation-tasks/tasks/staged-config.yml
    input_mapping:
      env: interpolated-files
    params:
      PRODUCT_NAME: ((products.pas.product_name))
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
      SUBSTITUTE_CREDENTIALS_WITH_PLACEHOLDERS: true
    on_success: &make-config-commit
      do:
        - task: make-commit
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: environment-automation
            file-source: generated-config
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: ((products.pas.product_name)).yml
            FILE_DESTINATION_PATH: ((foundation))/generated-config/((products.pas.product_name))-((products.pas.product_version))
            GIT_AUTHOR_EMAIL: ((github.user.email))
            GIT_AUTHOR_NAME: ((github.user.username))
            COMMIT_MESSAGE: "Add product config: ((products.pas.product_name))-((products.pas.product_version)).yml"
        - put: environment-automation
          params:
            repository: configuration-commit
            merge: true

- name: upload-stemcell-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [upload-and-stage-pas]
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
    - get: pas-stemcell
      params:
        globs:
        - "((products.pas.stemcell.product_globs))"
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: interpolated-files
      stemcell: pas-stemcell
    params:
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml

- name: generate-product-config-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [upload-and-stage-pas]
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: staged-config
    image: platform-automation-image
    file: platform-automation-tasks/tasks/staged-config.yml
    input_mapping:
      env: interpolated-files
    params:
      PRODUCT_NAME: ((products.pas.product_name))
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
      SUBSTITUTE_CREDENTIALS_WITH_PLACEHOLDERS: true
    on_success: &make-config-commit
      do:
        - task: make-commit
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: environment-automation
            file-source: generated-config
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: ((products.pas.product_name)).yml
            FILE_DESTINATION_PATH: ((foundation))/generated-config/((products.pas.product_name))-((products.pas.product_version))
            GIT_AUTHOR_EMAIL: ((github.user.email))
            GIT_AUTHOR_NAME: ((github.user.username))
            COMMIT_MESSAGE: "Add or update product config: ((products.pas.product_name))-((products.pas.product_version)).yml"
        - put: environment-automation
          params:
            repository: configuration-commit
            merge: true

- name: configure-product-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [generate-product-config-pas]
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: configure-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: environment-automation
      env: interpolated-files
      vars: interpolated-files
    params:
      CONFIG_FILE: ((foundation))/products/((products.pas.product_slug))
      VARS_FILES: vars/((foundation))/vars/((products.pas.product_slug)).yml
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml

- name: disable-errands-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [configure-product-pas]
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: configure-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: environment-automation
      env: interpolated-files
      vars: interpolated-files
    params:
      CONFIG_FILE: ((foundation))/products/((products.pas.product_slug))
      VARS_FILES: vars/((foundation))/vars/((products.pas.product_slug))-no-errans.yml
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml

- name: apply-product-changes-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [upload-stemcell-pas, configure-product-pas]
      #trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: apply-product-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
  - task: staged-config
    image: platform-automation-image
    file: platform-automation-tasks/tasks/staged-config.yml
    input_mapping:
      env: interpolated-files
    params:
      PRODUCT_NAME: ((products.pas.product_name))
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
      SUBSTITUTE_CREDENTIALS_WITH_PLACEHOLDERS: true
    on_success: *make-config-commit

- name: export-installation-pas
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [apply-product-changes-pas]
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: environment-automation
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: export-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/env/((products.pas.product_slug)).yml
      INSTALLATION_FILE: installation-after-((products.pas.product_slug))-((products.pas.product_version)).zip
  - put: installation
    params:
      file: installation/installation-after-((products.pas.product_slug))-((products.pas.product_version)).zip
